language: generic

sudo: required

env:
  PYTHON_VERSION="3.6.3"
  PACKAGE_VERSION="0.1.0"

before_install:
  - pyenv install ${PYTHON_VERSION} --skip-existing
  - pyenv global ${PYTHON_VERSION}
  - pip install pipenv

install:
  - PIPENV_YES=true pipenv install --dev
  - source $(pipenv --venv)/bin/activate
  - make dist

script:
  - dist/docker-job ajmazurie/probe:latest -- --format yaml --to-stdout

before_deploy:
  - mv dist/docker-job dist/docker_job-${TRAVIS_OS_NAME}

deploy:
  provider: releases
  api_key: "${GITHUB_TOKEN}"
  file: "dist/docker_job-${TRAVIS_OS_NAME}"
  skip_cleanup: true
  on:
    all_branches: true
    tags: true

notifications:
  email: false
  slack: "${SLACK_TOKEN}"
