language: generic

sudo: required

env:
  PYTHON_VERSION="3.6.3"
  PACKAGE_VERSION="0.1.0"

before_install:
  - pyenv install ${PYTHON_VERSION} --skip-existing && pyenv global ${PYTHON_VERSION}
  - pyenv exec pip install --upgrade --quiet --disable-pip-version-check pip pipenv

install:
  - PIPENV_YES=true pyenv exec pipenv install --dev
  - source $(pyenv exec pipenv --venv)/bin/activate
  - make dist

script:
  - dist/docker-job ajmazurie/probe:latest -- --format yaml --to-stdout

deploy:
  provider: releases
  api_key: "${GITHUB_TOKEN}"
  file: "dist/docker_job"
  skip_cleanup: true
  on:
    all_branches: true
    tags: true

notifications:
  email: false
  slack: "${SLACK_TOKEN}"
