language: generic
#os: [linux, osx]

sudo: required
#services: [docker]

before_install:
  - pyenv install 3.6.2 --skip-existing
  - pyenv global 3.6.2
  - pip install pipenv

install:
  - PIPENV_YES=true pipenv install --dev
  - source $(pipenv --venv)/bin/activate
  - make dist

script:
  - dist/docker-job ajmazurie/probe:latest -- --format yaml --to-stdout
